# FastGPTRAG微服务配置
rag:
  # RAG服务配置
  service:
    base_url: "http://fastgpt-rag:3001"
    timeout: 30s
    max_retries: 3
    auth_token: "${RAG_AUTH_TOKEN}"
    
  # 数据同步配置
  sync:
    enabled: true
    batch_size: 100
    interval: 5m
    auto_sync_on_create: true
    auto_sync_on_update: true
    
  # 搜索配置
  search:
    default_limit: 10
    max_limit: 100
    default_similarity: 0.6
    default_search_mode: "mixedRecall"
    enable_rerank: true
    default_rerank_model: "bge-reranker-base"
    
  # 模型配置
  models:
    embedding:
      default: "text-embedding-3-small"
      available: 
        - "text-embedding-3-small"
        - "text-embedding-3-large"
        - "text-embedding-ada-002"
    
    llm:
      default: "gpt-4o-mini"
      available:
        - "gpt-4o-mini"
        - "gpt-4o"
        - "gpt-3.5-turbo"
        
    rerank:
      default: "bge-reranker-base"
      available:
        - "bge-reranker-base"
        - "bge-reranker-large"
        - "cohere-rerank-multilingual"
        
  # 训练配置
  training:
    default_chunk_size: 512
    max_chunk_size: 2048
    default_training_type: "chunk"
    auto_start_training: true
    
  # 监控配置
  monitoring:
    enable_metrics: true
    metrics_interval: 60s
    enable_health_check: true
    health_check_interval: 30s
    
  # 缓存配置
  cache:
    enable_search_cache: true
    search_cache_ttl: 300s
    enable_embedding_cache: true
    embedding_cache_ttl: 3600s
