apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-es-secret
  labels:
    {{- include "opencoze.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.elasticsearch.username | b64enc | quote }}
  password: {{ .Values.elasticsearch.password | b64enc | quote }}