apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencoze.fullname" . }}-model-config
  labels:
    {{- include "opencoze.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "files/conf/*").AsConfig | nindent 2 }}