apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencoze.fullname" . }}-mysql
stringData:
  mysql-password: {{ .Values.mysql.password | quote }}
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}